#!/bin/bash
# =============================================================================
# configure-umbrel.sh — Auto-detect Umbrel's Bitcoin settings and write .env
# =============================================================================
# Run this ON your Umbrel box (via SSH), from the app directory:
#
#   cd ~/umbrel/home/bitcoin-after-life-will-executor     # (path may vary)
#   sudo bash scripts/configure-umbrel.sh
#
# It detects:
#   * Bitcoin Core container IP            (APP_BITCOIN_NODE_IP)
#   * RPC user / password                  (from bitcoin/.env)
#   * The Bitcoin data dir + cookie file   (APP_BITCOIN_DATA_DIR)
#   * The ZMQ hashblock port               (from bitcoin.conf, default 28334)
#
# It then writes a ready-to-use .env, preserving your existing
# BAL_BITCOIN_ADDRESS and BAL_BITCOIN_FEE if a .env already exists.
# =============================================================================

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${APP_DIR}/.env"

UMBREL_ROOT="${UMBREL_ROOT:-/home/umbrel/umbrel}"
BITCOIN_APP_DATA="${UMBREL_ROOT}/app-data/bitcoin"

log()  { echo "[configure] $*"; }
warn() { echo "[configure] WARNING: $*" >&2; }
die()  { echo "[configure] ERROR: $*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "docker not found. Run this on the Umbrel host."

# --- Preserve existing payment settings if present ---------------------------
OLD_ADDR=""
OLD_FEE=""
OLD_PUBURL=""
if [[ -f "${ENV_FILE}" ]]; then
  OLD_ADDR=$(grep -E '^BAL_BITCOIN_ADDRESS=' "${ENV_FILE}" | head -1 | cut -d= -f2- || true)
  OLD_FEE=$(grep -E '^BAL_BITCOIN_FEE=' "${ENV_FILE}" | head -1 | cut -d= -f2- || true)
  OLD_PUBURL=$(grep -E '^BAL_PUBLIC_URL=' "${ENV_FILE}" | head -1 | cut -d= -f2- || true)
  log "Existing .env found — keeping your address/fee/public-url."
fi

# --- 1. Detect Bitcoin Core container IP -------------------------------------
BTC_CONTAINER=$(docker ps --format '{{.Names}}' | grep -E '^bitcoin_app_1$' | head -1)
[[ -z "${BTC_CONTAINER}" ]] && BTC_CONTAINER=$(docker ps --format '{{.Names}}' | grep -iE 'bitcoin' | grep -ivE 'tor|proxy|i2p' | head -1)
[[ -z "${BTC_CONTAINER}" ]] && die "Could not find the Bitcoin Core container. Is the Bitcoin app installed?"

NODE_IP=$(docker inspect "${BTC_CONTAINER}" 2>/dev/null \
  | grep '"IPAddress"' | grep -oE '10\.[0-9]+\.[0-9]+\.[0-9]+' | head -1)
[[ -z "${NODE_IP}" ]] && NODE_IP=$(docker inspect "${BTC_CONTAINER}" 2>/dev/null \
  | grep -oE '"IPAddress": "[0-9.]+"' | grep -oE '[0-9.]+' | tail -1)
[[ -z "${NODE_IP}" ]] && die "Could not detect Bitcoin Core IP."
log "Bitcoin Core container: ${BTC_CONTAINER} @ ${NODE_IP}"

# --- 2. RPC credentials ------------------------------------------------------
RPC_USER="umbrel"
RPC_PASS=""
if [[ -r "${BITCOIN_APP_DATA}/.env" ]]; then
  RPC_USER=$(grep -E 'APP_BITCOIN_RPC_USER=' "${BITCOIN_APP_DATA}/.env" | head -1 | sed "s/.*=//; s/'//g" || true)
  RPC_PASS=$(grep -E 'APP_BITCOIN_RPC_PASS=' "${BITCOIN_APP_DATA}/.env" | head -1 | sed "s/.*=//; s/'//g" || true)
fi
[[ -z "${RPC_USER}" ]] && RPC_USER="umbrel"
log "RPC user: ${RPC_USER}"
[[ -z "${RPC_PASS}" ]] && warn "RPC password not found (cookie auth will still work)."

# --- 3. Bitcoin data dir + cookie --------------------------------------------
BTC_DATA_DIR=""
for d in \
  "${BITCOIN_APP_DATA}/data/bitcoin" \
  "${BITCOIN_APP_DATA}/data" \
  "${BITCOIN_APP_DATA}"; do
  if [[ -f "${d}/.cookie" || -f "${d}/bitcoin.conf" ]]; then
    BTC_DATA_DIR="${d}"
    break
  fi
done
[[ -z "${BTC_DATA_DIR}" ]] && warn "Bitcoin data dir not found — cookie auth may fail." \
  && BTC_DATA_DIR="${BITCOIN_APP_DATA}/data/bitcoin"
log "Bitcoin data dir: ${BTC_DATA_DIR}"

# --- 4. ZMQ hashblock port ---------------------------------------------------
ZMQ_PORT="28334"
CONF=""
for c in "${BTC_DATA_DIR}/bitcoin.conf" "${BTC_DATA_DIR}/umbrel-bitcoin.conf"; do
  [[ -r "$c" ]] && CONF="$c" && break
done
# umbrel-bitcoin.conf usually holds the real zmqpubhashblock line
UMBREL_CONF="${BTC_DATA_DIR}/umbrel-bitcoin.conf"
[[ -r "${UMBREL_CONF}" ]] && CONF="${UMBREL_CONF}"
if [[ -n "${CONF}" ]]; then
  DETECTED=$(grep -E '^zmqpubhashblock=' "${CONF}" | head -1 | grep -oE '[0-9]+$' || true)
  [[ -n "${DETECTED}" ]] && ZMQ_PORT="${DETECTED}"
fi
log "ZMQ hashblock port: ${ZMQ_PORT}"

# --- 5. Write .env -----------------------------------------------------------
ADDR="${OLD_ADDR:-}"
FEE="${OLD_FEE:-30000}"
PUBURL="${OLD_PUBURL:-}"

cat > "${ENV_FILE}" <<EOF
# Auto-generated by scripts/configure-umbrel.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Edit BAL_BITCOIN_ADDRESS / BAL_BITCOIN_FEE / BAL_PUBLIC_URL as needed.

BAL_BITCOIN_ADDRESS=${ADDR}
BAL_BITCOIN_FEE=${FEE}

APP_BITCOIN_NODE_IP=${NODE_IP}
APP_BITCOIN_RPC_PORT=8332
APP_BITCOIN_RPC_USER=${RPC_USER}
APP_BITCOIN_RPC_PASS=${RPC_PASS}

BAL_ZMQ_PORT=${ZMQ_PORT}
BAL_PUSHER_BITCOIN_ZMQ_HASHBLOCK=tcp://${NODE_IP}:${ZMQ_PORT}

APP_BITCOIN_DATA_DIR=${BTC_DATA_DIR}
BAL_PUSHER_BITCOIN_COOKIE_FILE=/bitcoin-data/.cookie

# Persistent storage: bal.db, keys and zmq-status.json are saved here on the host.
APP_DATA_DIR=${UMBREL_ROOT}/app-data/bal-will

BAL_PUBLIC_URL=${PUBURL}

APP_PORT=9140
BAL_LOG_LEVEL=info
BAL_PUSHER_NETWORK=bitcoin
BAL_SEND_STATS=false
EOF

log "Wrote ${ENV_FILE}"
echo ""
log "Done. Review the file, then run:"
log "  sudo docker compose up -d --build"
log "  sudo bash scripts/install-service.sh   # auto-start on reboot"
if [[ -z "${ADDR}" ]]; then
  echo ""
  warn "BAL_BITCOIN_ADDRESS is empty — edit .env and set your bc1q... address"
  warn "to collect fees, or leave empty to run for free."
fi
